version: '3'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./authuser_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Info@123
      POSTGRES_DB: ead-authuser-v2
