
spring:
  application:
    name: ead-authuser-service
  config:
    activate:
      on-profile: dev
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: configserver
      password: 'ead123cs'
